name: tests

on:
  push:
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install -s --no-progress --non-interactive
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install -s --no-progress --non-interactive
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn serve
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-snapshots-${{ matrix.browser }}
          path: tests/e2e/specs/__image_snapshots__
