name: tests

on:
  push:
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install -s --no-progress --non-interactive
      - name: Lint
        run: yarn lint
      - name: Build package
        run: yarn lib:build
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install -s --no-progress --non-interactive
      - name: Unit tests
        run: yarn test:unit:coverage
      - name: Store unit coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-unit
          path: coverage-unit
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install -s --no-progress --non-interactive
      - name: E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: yarn demo:build
          start: yarn demo:preview
          wait-on: http://localhost:4173
      - name: Store e2e coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-e2e
          path: coverage-e2e
      - name: Store Cypress snapshots artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: tests/e2e/specs/__image_snapshots__
  upload-coverage:
    name: upload-coverage
    needs: [ unit-tests, e2e-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download unit coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-unit
          path: coverage/coverage-unit
      - name: Download e2e coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-e2e
          path: coverage/coverage-e2e
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: coverage
